### ISSUE TITLE
Hard coded tokens

### ISSUE THREAD

**Issue by oz123** [valentin2105/Kubernetes-Saltstack#13]
The Pillar information has hard coded information:

https://github.com/valentin2105/Kubernetes-Saltstack/blob/be176eb714e523096369841e6a1538b4f77326cc/pillar/cluster_config.sls#L52

This should be removed and explicitly added by the user of the formula.

**Comment by oz123** [comment]
SORRY, you do document this issue, but its hard to miss change me in the middle.
It's better if you simply remove those strings.

**Comment by valentin2105** [comment]
Good, Idea, I will update the readme to generate the Token, and delete it in the Pillar.
