### ISSUE TITLE
supported docker version should be fixed

### ISSUE THREAD

**Issue by oz123** [valentin2105/Kubernetes-Saltstack#14]
According to Kubernetes release notes the latest tested version for kubernetes is: 17.03

see https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.10.md#external-dependencies.

https://github.com/valentin2105/Kubernetes-Saltstack/blob/4499c8c1a417227c66b9c7b4f1aa3033bf0e9a72/pillar/cluster_config.sls#L26

This should be updated accordingly to 17.03 from 18.03

**Comment by valentin2105** [comment]
@oz123  You're true, it work but can cause issues.  

I will try rollback to 17.03 and then commit that.

**Comment by valentin2105** [comment]
@oz123  We're now in K8S 1.16.1 and Docker 18.09.9, as recommended on the Documentation.
