### ISSUE TITLE
Can I change out the calico for something like weavenet?

### ISSUE THREAD

**Issue by mjschmidt** [valentin2105/Kubernetes-Saltstack#16]
Just a quick how to question.

**Comment by valentin2105** [comment]
Hi @mjschmidt 

If you want not use Calico, you can comment the line 24 and 25 of `k8s-worker/cni/init.sls `

Then, you can install your cluster using Kubernetes-Saltstack recipe. 

To install Weave net after that, simply follow their documentation : 
https://www.weave.works/docs/net/latest/kubernetes/kube-addon/

If you want use the post_install script, comment line 11 and 12, install weavenet, then launch the `./post-install/setup.sh` script.
