### ISSUE TITLE
post_install/setup.sh doesn t need to be on the salt master

### ISSUE THREAD

**Issue by rgroux** [valentin2105/Kubernetes-Saltstack#18]
hi, 
I read your post install setup because i want to know why the salt master and K8s need to be on the same host.
you write:
> The configuration is done to use the Salt-master as the Kubernetes master. You can have them as different nodes if needed but the post_install/script.sh require kubectl and access to the pillar files

but in fact this is not nessessary, because you can use salt-call pillar.get to retrived the data instead of `cat files | grep` ...

```bash
HELM_VERSION=$(cat /srv/salt/pillar/cluster_config.sls |grep helm-version |sed  's/^.*: //g')
CLUSTER_DOMAIN=$(cat /srv/salt/pillar/cluster_config.sls |grep domain |head -n 1 |sed  's/^.*: //g')
```
to be change to

```bash
HELM_VERSION=`salt-call pillar.get --out=txt kubernetes:global:helm-version |cut -d ' ' -f 2`
CLUSTER_DOMAIN=`salt-call pillar.get --out=txt kubernetes:domain |cut -d ' ' -f 2`
```
or even better, you can generate a file from a template and populate with valid value of HELM_VERSION and  CLUSTER_DOMAIN with something like `salt['pillar.get']('kubernetes:global:helm')`

so, like this you can reduce the adherance of puppet master and kubernetes master

**Comment by valentin2105** [comment]
Hi @rgroux ,

Great Idea, to be honest at the moment of the conception I haven't think a lot about this part. 

Would you submit a PR to fix that ? (if you tested this part) 

If you can't, I will do that but I need to finish my current work, to upgrade k8s version and fix few things.

**Comment by rgroux** [comment]
@valentin2105 

ok, i will try it soon,.
this week i hope, because i am french, work in France and May like August is nice to try new ideas :)

BTW thanks for the formulas

**Comment by rgroux** [comment]
@valentin2105 

it seems ok, and work as expected.
i need to refactor few thins about sls path like 

```yaml
include:
  - k8s-master/etcd
```
to
```yaml
include:
  -.etcd
```
and stuff like this.
refactor  the top.sls to an init.sls

then make a nice PR with good commit message and changelog

/Richard

**Comment by rgroux** [comment]
i create some patch and make a PR #19 as pre requisits for a relocation outside the k8 master
then i will make a PR for using pillar inside the setup.sh and templates to generate those files on the K8 master server.

**Comment by rgroux** [comment]
#21 merged
