### ISSUE TITLE
Kubernetes Cluster Upgrade

### ISSUE THREAD

**Issue by coolpalani** [valentin2105/Kubernetes-Saltstack#24]
Hi,

Looks like cluster setup automation in older version. could you plan and upgrade to new stable version

**Comment by rgroux** [comment]
i will reply even if i am not the maintener of this repo.

you can set the version you want to use with the pillar parameters, it s very easy to setup, look at the kubernetes requirement/version of component that can suit your needs.

**Comment by valentin2105** [comment]
Hi @coolpalani ,

I'm currently working to release an up-to-date commit with etcd/k8s updated, but I need some time to finish.
As @rgroux said, you can easily tweak the k8s version, but you'll have to check if nothing is broken with the current setup (systemd services  manifest).

**Comment by rgroux** [comment]
Hi all, 
@valentin2105 and @coolpalani , in fact it's esy to tweak, but the not so easy to validtare the combinaison of version.

At first, i try  to use the last stable version of each part, and naïvely i hope it will works, but the calico part was into a crashloop. 

i did this before read the [realease notes](https://kubernetes.io/docs/setup/release/#changed)

so we can start to check with this version of components

  - kubernetes: v1.15
  - etcd: v3.3.10
  - docker: 18.09
  - cni: v0.7.5
  - calico: v3.3.1
  - dashboard: v1.10.1

but we need to parametrize some deployment like coredns to choose the version of installation

  - coredns: v1.2.0 ->  v1.3.1
  - grafana: v4.4.3 -> OK
  - influxdb: v1.3.3 -> OK

**Comment by coolpalani** [comment]
@valentin2105 @rgroux 
Please review my PR https://github.com/valentin2105/Kubernetes-Saltstack/pull/26 and merge it.

**Comment by valentin2105** [comment]
@coolpalani  If you can finish your PR please.
