### ISSUE TITLE
Deployment error message

### ISSUE THREAD

**Issue by coolpalani** [valentin2105/Kubernetes-Saltstack#25]
Hello,

I'm getting the following error message.

----------
          ID: /opt/calico.yaml
    Function: file.managed
      Result: False
     Comment: Source file salt://k8s-master/k8s-worker/cni/calico/calico.tmpl.yaml not found in saltenv 'base'
     Started: 13:32:42.478875
    Duration: 3.712 ms
     Changes:
----------
          ID: /opt/kubernetes/post_install/coredns.yaml
    Function: file.managed
      Result: False
     Comment: Source file salt://k8s-master/post_install/coredns.yaml not found in saltenv 'base'
     Started: 13:32:42.482760
    Duration: 3.701 ms
     Changes:
----------

To resolve this above problem, I tried to make symlink and it works

cd /srv/salt/k8s-master/
ln -s /srv/salt/post_install/ post_install

k8s-master part is working but I'm still getting the following error message in worker node.

----------
          ID: /opt/cni/bin/calico
    Function: file.managed
      Result: False
     Comment: The following requisites were not found:
                                 require:
                                     sls: k8s-worker.k8s-worker.cni
     Started: 13:32:49.196706
    Duration: 0.014 ms
     Changes:
----------
          ID: /opt/cni/bin/calico-ipam
    Function: file.managed
      Result: False
     Comment: The following requisites were not found:
                                 require:
                                     sls: k8s-worker.k8s-worker.cni
     Started: 13:32:49.197108
    Duration: 0.01 ms
     Changes:
----------

Could you please update the readme file if it's not updated.

**Comment by coolpalani** [comment]
@valentin2105 

I tried to remove .worker keyword in following files and able to deploy.

https://github.com/valentin2105/Kubernetes-Saltstack/blob/master/k8s-worker/cni/calico/init.sls#L35
https://github.com/valentin2105/Kubernetes-Saltstack/blob/master/k8s-worker/cni/calico/init.sls#L49
https://github.com/valentin2105/Kubernetes-Saltstack/blob/master/k8s-worker/cni/calico/init.sls#L59
https://github.com/valentin2105/Kubernetes-Saltstack/blob/master/k8s-worker/cni/calico/init.sls#L69

But please correct me whether the process is correct or not.

**Comment by rgroux** [comment]
Hi @coolpalani,

i will check it ASAP, not this week, it s not possible, but next week (after 7 of July 2019).

**Comment by rgroux** [comment]
hello @coolpalani 

can i have more information about the salt base structure of the folder? i think i have a idea about the problem.

i need to know:
  - salt master is on the kubernetes cluster or oustside?
  - the tree structure from the root of the state_top
  - the result of the command show_sls of the state.

```bash
salt-call state.show_sls <path.to.the.state>.k8s-master
```

**Comment by coolpalani** [comment]
Hello @rgroux 

I configured saltmaster in the kubernetes master itself.
I cloned entire this repo code under in /srv/salt and linked pillar directory 

git clone https://github.com/valentin2105/Kubernetes-Saltstack.git /srv/salt
ln -s /srv/salt/pillar /srv/pillar

Master bootstrap

curl -L https://bootstrap.saltstack.com -o install_salt
chmod +x install_salt
./install_salt -M

### Kubernetes master & workers
cat << EOF > /etc/salt/grains
role: 
  - k8s-master
  - k8s-worker
EOF

service salt-minion restart 

Worker bootstrap

curl -L https://bootstrap.saltstack.com -o install_salt
chmod +x install_salt
./install_salt -A saltmasterip -i workernodename

salt -G 'role:k8s-master' state.highstate 
salt -G 'role:k8s-worker' state.highstate

I hope you would have get some idea of the problem.

**Comment by rgroux** [comment]
@coolpalani 
actually not sure about the problem, because not time this week, but just think about it and i collect al the possible ideas and information about this issue.

BTW, you give me a way to reproduce the issue, so it will be easier to debug. thanks.
and i think the bug is around:  

```bash
salt://{{ slspath.split('/')[0] }}/k8s-worker/cni/calico/calico.tmpl.yaml -> salt://k8s-master/k8s-worker/cni/calico/calico.tmpl.yaml
```

instead of 

```bash
salt://{{ slspath.split('/')[0] }}/k8s-worker/cni/calico/calico.tmpl.yaml -> salt:///k8s-master/k8s-worker/cni/calico/calico.tmpl.yaml
```
the `slspath.split('/')[0]` is `k8s-master` but should be `/k8s-master`, in the case of direct clone of the git repo, serving  files with `salt:///` because `salt://k8s-master` is not correct


I am not sure i am clear, but in my mind it is :) so if it is what i write before, it have a quick&dirty patch for it, you can try with adding a leading / to all `salt://{{ slspath.split('/')[0] }}` (only for Q&D not for PR)

The hard way will be to find a way to detect the real root of states. The issue will be solve very soon.

ADD: it's only 2 entries in k8s-master/init.sls at line 85 and 95, 


/Richard

**Comment by rgroux** [comment]
@coolpalani 

coud you try to make a symlink 

```bash
ln -s /srv/salt/k8s-master /srv/salt/k8s-master/k8s-master
```
this little change will correct the issue for you
and now i am pretty sure how to change it and make a nice PR

**Comment by valentin2105** [comment]
Fixed  by @rgroux .
