### ISSUE TITLE
kube-apiserver, kube-controller, kube-scheduler, etcd as a system process

### ISSUE THREAD

**Issue by srinivasnddevops** [valentin2105/Kubernetes-Saltstack#28]
Team,
why kube-apiserver, kube-controller, kube-scheduler, etcd is deployed as a system process? why we are not deploying as a containers with this saltstack code?

As a production standard whether running kubesystem process like kube-apiserver, kube-controller, kube-scheduler, etcd as a system process is better or running pods as better?

**Comment by valentin2105** [comment]
Hi @srinivasnddevops 
Sorry for the answer delay,

It's a design choice, I think run Kubernetes components in SystemD Unit give some great advantage, like syslog logging, start at boot, easy managing via service commands (...) and it's really stable.

I think to production use, run in systemD unit is a good choice.
