### ISSUE TITLE
Feature Request: Weave CNI

### ISSUE THREAD

**Issue by mmisztal1980** [valentin2105/Kubernetes-Saltstack#5]
As title says, I'm liking this recipe a lot. IMHO it would be very cool if it included Weave.

**Comment by valentin2105** [comment]
Hi @mmisztal1980 

Good Idea, I'm not a big user of Weave, but I could try to implement that. 
But I will finish first to allow enable master H/A & k8s v.1.9. 

I keep this open to track ;)
