### ISSUE TITLE
Feature request: Upgrade to kubernetes 1.10

### ISSUE THREAD

**Issue by mmisztal1980** [valentin2105/Kubernetes-Saltstack#7]
As title says, Currently we're targeting 1.8.6, adding the latest version would be nice

**Comment by valentin2105** [comment]
Hi,

I'm planning to move the default to v1.9.x and make 1.10 work too !

I will try to do that as soon as possible :smile: 

Feel free to report any bug or feature request ;)

**Comment by mmisztal1980** [comment]
btw, I'm working on a solution based on yours, perhaps it would be cool to sync-up in the near future and share what I have (reactor-based solution)

**Comment by valentin2105** [comment]
Done @mmisztal1980 . :smile:
