### ISSUE TITLE
Persistence Volume Provisioning on GCP

### ISSUE THREAD

**Issue by coolpalani** [valentin2105/Kubernetes-Saltstack#9]
I have deployed the Kubernetes cluster on GCP. I am struck in provision storage (gcePersistentDisk)
Could you provide some info
Or else is there any simple way to provision dynamic storage (gcePersistentDisk) in K8s

Thank in advance.

**Comment by valentin2105** [comment]
Hi @coolpalani 
The goal of this project is to be fully Cloud-provider agnostic,
but maybe I can add the support of GCE LoadBalancer and PersistendDisk, but I'll need small time to figure it out. 

I keep this issue open.

**Comment by coolpalani** [comment]
Thank you very much for taking it as request.
This link may be helpful when you are working on that part.

https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/

Demonstration for AWS cloud

https://medium.com/ai-software-engineering-blog/kubernetes-on-aws-6281e3a830fe
https://stackoverflow.com/questions/36629896/setting-cloudprovider-after-installation

**Comment by valentin2105** [comment]
Hi @coolpalani ,

After few digging, it seem using gcePersistentDisk on k8s-GCE, without using GKE is not possible..
You need to write a tool that watch for PVC, create disk ...

Say me if you find answers on this side.

**Comment by coolpalani** [comment]
I couldn't find much details. How about Google Cloud LoadBalancer if I want create and attach it with our cluster. Is this also same on k8s-GCE, without using GKE is not possible.

For Persistence storage (self host solutions), We can even go with either openebs based solutions or rook which is based on CEPH storage

**Comment by valentin2105** [comment]
I close this issue because is GKE related, for persistant storage on own deployment method, we need to check about Ceph, GlusterFS, Rook.io (...) 

=)
